package hibernate.entity;
// Generated May 14, 2014 9:49:53 PM by Hibernate Tools 3.6.0


import hibernate.until.HibernateUtil;
import java.io.Serializable;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int accountId;
     private String username;
     private String passwords;
     private String roles;

    public Account() {
    }

	
    public Account(int accountId, String username, String passwords) {
        this.accountId = accountId;
        this.username = username;
        this.passwords = passwords;
    }
    public Account(int accountId, String username, String passwords, String roles) {
       this.accountId = accountId;
       this.username = username;
       this.passwords = passwords;
       this.roles = roles;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }
//public static void main(String[] args)
//    {
//        Account acc = new Account();
//        acc.setUsername("duy");
//        acc.setPasswords("123456");
//        acc.setRoles("guest");
//        SessionFactory factory = HibernateUtil.getSessionFactory();
//        Session session = factory.getCurrentSession();
//        try{
//            session.beginTransaction();
//            session.save(acc);
//            session.getTransaction().commit();
//            
//            
//        }catch(Exception e)
//        {
//            if(session.getTransaction().isActive())
//            {
//                session.getTransaction().rollback();
//            }
//            e.printStackTrace();
//        }
//    }



}


