package hibernate.entity;
// Generated May 15, 2014 10:06:42 PM by Hibernate Tools 3.6.0



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer accountId;
     private String username;
     private String passwords;
     private String roles;

    public Account() {
    }

	
    public Account(String username, String passwords) {
        this.username = username;
        this.passwords = passwords;
    }
    public Account(String username, String passwords, String roles) {
       this.username = username;
       this.passwords = passwords;
       this.roles = roles;
    }
   
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }




}


