package hibernate.entity;
// Generated May 18, 2014 12:37:30 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Classs generated by hbm2java
 */
public class Classs  implements java.io.Serializable {


     private int classId;
     private String className;
     private Set<Student> students = new HashSet<Student>(0);

    public Classs() {
    }

	
    public Classs(int classId) {
        this.classId = classId;
    }
    public Classs(int classId, String className, Set<Student> students) {
       this.classId = classId;
       this.className = className;
       this.students = students;
    }
   
    public int getClassId() {
        return this.classId;
    }
    
    public void setClassId(int classId) {
        this.classId = classId;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


