package hibernate.entity;
// Generated May 15, 2014 10:06:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Classs generated by hbm2java
 */
public class Classs  implements java.io.Serializable {


     private Integer classId;
     private Semester semester;
     private String className;
     private Set<Student> students = new HashSet<Student>(0);

    public Classs() {
    }

    public Classs(Semester semester, String className, Set<Student> students) {
       this.semester = semester;
       this.className = className;
       this.students = students;
    }
   
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }




}


