package hibernate.entity;
// Generated May 15, 2014 10:06:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Curriculum generated by hbm2java
 */
public class Curriculum  implements java.io.Serializable {


     private Integer curriculumId;
     private String curriculumName;
     private Set<Semester> semesters = new HashSet<Semester>(0);

    public Curriculum() {
    }

	
    public Curriculum(String curriculumName) {
        this.curriculumName = curriculumName;
    }
    public Curriculum(String curriculumName, Set<Semester> semesters) {
       this.curriculumName = curriculumName;
       this.semesters = semesters;
    }
   
    public Integer getCurriculumId() {
        return this.curriculumId;
    }
    
    public void setCurriculumId(Integer curriculumId) {
        this.curriculumId = curriculumId;
    }
    public String getCurriculumName() {
        return this.curriculumName;
    }
    
    public void setCurriculumName(String curriculumName) {
        this.curriculumName = curriculumName;
    }
    public Set<Semester> getSemesters() {
        return this.semesters;
    }
    
    public void setSemesters(Set<Semester> semesters) {
        this.semesters = semesters;
    }




}


