package hibernate.entity;
// Generated May 30, 2014 8:57:36 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CurriculumSemester generated by hbm2java
 */
public class CurriculumSemester  implements java.io.Serializable {


     private int curSemId;
     private Semester semester;
     private Curriculum curriculum;
     private String term;
     private Set<SemesterSubject> semesterSubjects = new HashSet<SemesterSubject>(0);

    public CurriculumSemester() {
    }

	
    public CurriculumSemester(int curSemId) {
        this.curSemId = curSemId;
    }
    public CurriculumSemester(int curSemId, Semester semester, Curriculum curriculum, String term, Set<SemesterSubject> semesterSubjects) {
       this.curSemId = curSemId;
       this.semester = semester;
       this.curriculum = curriculum;
       this.term = term;
       this.semesterSubjects = semesterSubjects;
    }
   
    public int getCurSemId() {
        return this.curSemId;
    }
    
    public void setCurSemId(int curSemId) {
        this.curSemId = curSemId;
    }
    public Semester getSemester() {
        return this.semester;
    }
    
    public void setSemester(Semester semester) {
        this.semester = semester;
    }
    public Curriculum getCurriculum() {
        return this.curriculum;
    }
    
    public void setCurriculum(Curriculum curriculum) {
        this.curriculum = curriculum;
    }
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }
    public Set<SemesterSubject> getSemesterSubjects() {
        return this.semesterSubjects;
    }
    
    public void setSemesterSubjects(Set<SemesterSubject> semesterSubjects) {
        this.semesterSubjects = semesterSubjects;
    }




}


