package hibernate.entity;
// Generated May 30, 2014 8:57:36 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Curriculum generated by hbm2java
 */
public class Curriculum  implements java.io.Serializable {


     private int curriculumId;
     private String curriculumName;
     private Set<CurriculumSemester> curriculumSemesters = new HashSet<CurriculumSemester>(0);

    public Curriculum() {
    }

	
    public Curriculum(int curriculumId, String curriculumName) {
        this.curriculumId = curriculumId;
        this.curriculumName = curriculumName;
    }
    public Curriculum(int curriculumId, String curriculumName, Set<CurriculumSemester> curriculumSemesters) {
       this.curriculumId = curriculumId;
       this.curriculumName = curriculumName;
       this.curriculumSemesters = curriculumSemesters;
    }
   
    public int getCurriculumId() {
        return this.curriculumId;
    }
    
    public void setCurriculumId(int curriculumId) {
        this.curriculumId = curriculumId;
    }
    public String getCurriculumName() {
        return this.curriculumName;
    }
    
    public void setCurriculumName(String curriculumName) {
        this.curriculumName = curriculumName;
    }
    public Set<CurriculumSemester> getCurriculumSemesters() {
        return this.curriculumSemesters;
    }
    
    public void setCurriculumSemesters(Set<CurriculumSemester> curriculumSemesters) {
        this.curriculumSemesters = curriculumSemesters;
    }




}


