package hibernate.entity;
// Generated May 21, 2014 5:40:05 PM by Hibernate Tools 3.6.0



/**
 * MarksId generated by hbm2java
 */
public class MarksId  implements java.io.Serializable {


     private int studentId;
     private int subjectId;

    public MarksId() {
    }

    public MarksId(int studentId, int subjectId) {
       this.studentId = studentId;
       this.subjectId = subjectId;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MarksId) ) return false;
		 MarksId castOther = ( MarksId ) other; 
         
		 return (this.getStudentId()==castOther.getStudentId())
 && (this.getSubjectId()==castOther.getSubjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getSubjectId();
         return result;
   }   


}


