package hibernate.entity;
// Generated May 30, 2014 8:57:36 PM by Hibernate Tools 3.6.0



/**
 * MarksId generated by hbm2java
 */
public class MarksId  implements java.io.Serializable {


     private int studentId;
     private int semSubjId;

    public MarksId() {
    }

    public MarksId(int studentId, int semSubjId) {
       this.studentId = studentId;
       this.semSubjId = semSubjId;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public int getSemSubjId() {
        return this.semSubjId;
    }
    
    public void setSemSubjId(int semSubjId) {
        this.semSubjId = semSubjId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MarksId) ) return false;
		 MarksId castOther = ( MarksId ) other; 
         
		 return (this.getStudentId()==castOther.getStudentId())
 && (this.getSemSubjId()==castOther.getSemSubjId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getSemSubjId();
         return result;
   }   


}


