package hibernate.entity;
// Generated May 30, 2014 8:57:36 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marks generated by hbm2java
 */
public class Marks  implements java.io.Serializable {


     private MarksId id;
     private SemesterSubject semesterSubject;
     private Student student;
     private Integer mark;
     private Integer updatedTime;
     private Date testDate;
     private String isPassed;
     private String isReevaluated;
     private Set<ReEvaluation> reEvaluations = new HashSet<ReEvaluation>(0);

    public Marks() {
    }

	
    public Marks(MarksId id, SemesterSubject semesterSubject, Student student) {
        this.id = id;
        this.semesterSubject = semesterSubject;
        this.student = student;
    }
    public Marks(MarksId id, SemesterSubject semesterSubject, Student student, Integer mark, Integer updatedTime, Date testDate, String isPassed, String isReevaluated, Set<ReEvaluation> reEvaluations) {
       this.id = id;
       this.semesterSubject = semesterSubject;
       this.student = student;
       this.mark = mark;
       this.updatedTime = updatedTime;
       this.testDate = testDate;
       this.isPassed = isPassed;
       this.isReevaluated = isReevaluated;
       this.reEvaluations = reEvaluations;
    }
   
    public MarksId getId() {
        return this.id;
    }
    
    public void setId(MarksId id) {
        this.id = id;
    }
    public SemesterSubject getSemesterSubject() {
        return this.semesterSubject;
    }
    
    public void setSemesterSubject(SemesterSubject semesterSubject) {
        this.semesterSubject = semesterSubject;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }
    public Integer getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Integer updatedTime) {
        this.updatedTime = updatedTime;
    }
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }
    public String getIsPassed() {
        return this.isPassed;
    }
    
    public void setIsPassed(String isPassed) {
        this.isPassed = isPassed;
    }
    public String getIsReevaluated() {
        return this.isReevaluated;
    }
    
    public void setIsReevaluated(String isReevaluated) {
        this.isReevaluated = isReevaluated;
    }
    public Set<ReEvaluation> getReEvaluations() {
        return this.reEvaluations;
    }
    
    public void setReEvaluations(Set<ReEvaluation> reEvaluations) {
        this.reEvaluations = reEvaluations;
    }




}


