package hibernate.entity;
// Generated May 14, 2014 9:49:53 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * Mark generated by hbm2java
 */
public class Mark  implements java.io.Serializable {


     private MarkId id;
     private Student student;
     private Subjects subjects;
     private Integer mark;
     private Date testDate;
     private String isReleased;
     private String isPass;
     private String reEvaluation;

    public Mark() {
    }

	
    public Mark(MarkId id, Student student, Subjects subjects) {
        this.id = id;
        this.student = student;
        this.subjects = subjects;
    }
    public Mark(MarkId id, Student student, Subjects subjects, Integer mark, Date testDate, String isReleased, String isPass, String reEvaluation) {
       this.id = id;
       this.student = student;
       this.subjects = subjects;
       this.mark = mark;
       this.testDate = testDate;
       this.isReleased = isReleased;
       this.isPass = isPass;
       this.reEvaluation = reEvaluation;
    }
   
    public MarkId getId() {
        return this.id;
    }
    
    public void setId(MarkId id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }
    public String getIsReleased() {
        return this.isReleased;
    }
    
    public void setIsReleased(String isReleased) {
        this.isReleased = isReleased;
    }
    public String getIsPass() {
        return this.isPass;
    }
    
    public void setIsPass(String isPass) {
        this.isPass = isPass;
    }
    public String getReEvaluation() {
        return this.reEvaluation;
    }
    
    public void setReEvaluation(String reEvaluation) {
        this.reEvaluation = reEvaluation;
    }




}


