package hibernate.entity;
// Generated May 15, 2014 10:06:42 PM by Hibernate Tools 3.6.0



/**
 * MarkId generated by hbm2java
 */
public class MarkId  implements java.io.Serializable {


     private Integer studentId;
     private Integer subjectId;

    public MarkId() {
    }

    public MarkId(Integer studentId, Integer subjectId) {
       this.studentId = studentId;
       this.subjectId = subjectId;
    }
   
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }




}


