package hibernate.entity;
// Generated May 18, 2014 12:37:30 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marks generated by hbm2java
 */
public class Marks  implements java.io.Serializable {


     private int marksId;
     private Student student;
     private Subjects subjects;
     private Integer mark;
     private Date testDate;
     private String isReleased;
     private String isPass;
     private String reEvaluation;
     private Set<ReEvaluation> reEvaluations = new HashSet<ReEvaluation>(0);

    public Marks() {
    }

	
    public Marks(int marksId) {
        this.marksId = marksId;
    }
    public Marks(int marksId, Student student, Subjects subjects, Integer mark, Date testDate, String isReleased, String isPass, String reEvaluation, Set<ReEvaluation> reEvaluations) {
       this.marksId = marksId;
       this.student = student;
       this.subjects = subjects;
       this.mark = mark;
       this.testDate = testDate;
       this.isReleased = isReleased;
       this.isPass = isPass;
       this.reEvaluation = reEvaluation;
       this.reEvaluations = reEvaluations;
    }
   
    public int getMarksId() {
        return this.marksId;
    }
    
    public void setMarksId(int marksId) {
        this.marksId = marksId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }
    public String getIsReleased() {
        return this.isReleased;
    }
    
    public void setIsReleased(String isReleased) {
        this.isReleased = isReleased;
    }
    public String getIsPass() {
        return this.isPass;
    }
    
    public void setIsPass(String isPass) {
        this.isPass = isPass;
    }
    public String getReEvaluation() {
        return this.reEvaluation;
    }
    
    public void setReEvaluation(String reEvaluation) {
        this.reEvaluation = reEvaluation;
    }
    public Set<ReEvaluation> getReEvaluations() {
        return this.reEvaluations;
    }
    
    public void setReEvaluations(Set<ReEvaluation> reEvaluations) {
        this.reEvaluations = reEvaluations;
    }




}


