package hibernate.entity;
// Generated May 21, 2014 5:40:05 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marks generated by hbm2java
 */
public class Marks  implements java.io.Serializable {


     private MarksId id;
     private Student student;
     private Subjects subjects;
     private Integer mark;
     private Date testDate;
     private String isPassed;
     private String isReevaluated;
     private Set<ReEvaluation> reEvaluations = new HashSet<ReEvaluation>(0);

    public Marks() {
    }

	
    public Marks(MarksId id, Student student, Subjects subjects) {
        this.id = id;
        this.student = student;
        this.subjects = subjects;
    }
    public Marks(MarksId id, Student student, Subjects subjects, Integer mark, Date testDate, String isPassed, String isReevaluated, Set<ReEvaluation> reEvaluations) {
       this.id = id;
       this.student = student;
       this.subjects = subjects;
       this.mark = mark;
       this.testDate = testDate;
       this.isPassed = isPassed;
       this.isReevaluated = isReevaluated;
       this.reEvaluations = reEvaluations;
    }
   
    public MarksId getId() {
        return this.id;
    }
    
    public void setId(MarksId id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public Integer getMark() {
        return this.mark;
    }
    
    public void setMark(Integer mark) {
        this.mark = mark;
    }
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }
    public String getIsPassed() {
        return this.isPassed;
    }
    
    public void setIsPassed(String isPassed) {
        this.isPassed = isPassed;
    }
    public String getIsReevaluated() {
        return this.isReevaluated;
    }
    
    public void setIsReevaluated(String isReevaluated) {
        this.isReevaluated = isReevaluated;
    }
    public Set<ReEvaluation> getReEvaluations() {
        return this.reEvaluations;
    }
    
    public void setReEvaluations(Set<ReEvaluation> reEvaluations) {
        this.reEvaluations = reEvaluations;
    }




}


