package hibernate.entity;
// Generated May 18, 2014 12:37:30 PM by Hibernate Tools 3.6.0



/**
 * ReEvaluation generated by hbm2java
 */
public class ReEvaluation  implements java.io.Serializable {


     private int reEvaluationId;
     private Marks marks;
     private Integer states;

    public ReEvaluation() {
    }

	
    public ReEvaluation(int reEvaluationId) {
        this.reEvaluationId = reEvaluationId;
    }
    public ReEvaluation(int reEvaluationId, Marks marks, Integer states) {
       this.reEvaluationId = reEvaluationId;
       this.marks = marks;
       this.states = states;
    }
   
    public int getReEvaluationId() {
        return this.reEvaluationId;
    }
    
    public void setReEvaluationId(int reEvaluationId) {
        this.reEvaluationId = reEvaluationId;
    }
    public Marks getMarks() {
        return this.marks;
    }
    
    public void setMarks(Marks marks) {
        this.marks = marks;
    }
    public Integer getStates() {
        return this.states;
    }
    
    public void setStates(Integer states) {
        this.states = states;
    }




}


