package hibernate.entity;
// Generated May 30, 2014 8:57:36 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * ReEvaluation generated by hbm2java
 */
public class ReEvaluation  implements java.io.Serializable {


     private int reEvaluationId;
     private Marks marks;
     private Integer oldMark;
     private String isUpdated;
     private Date registeredDate;

    public ReEvaluation() {
    }

	
    public ReEvaluation(int reEvaluationId) {
        this.reEvaluationId = reEvaluationId;
    }
    public ReEvaluation(int reEvaluationId, Marks marks, Integer oldMark, String isUpdated, Date registeredDate) {
       this.reEvaluationId = reEvaluationId;
       this.marks = marks;
       this.oldMark = oldMark;
       this.isUpdated = isUpdated;
       this.registeredDate = registeredDate;
    }
   
    public int getReEvaluationId() {
        return this.reEvaluationId;
    }
    
    public void setReEvaluationId(int reEvaluationId) {
        this.reEvaluationId = reEvaluationId;
    }
    public Marks getMarks() {
        return this.marks;
    }
    
    public void setMarks(Marks marks) {
        this.marks = marks;
    }
    public Integer getOldMark() {
        return this.oldMark;
    }
    
    public void setOldMark(Integer oldMark) {
        this.oldMark = oldMark;
    }
    public String getIsUpdated() {
        return this.isUpdated;
    }
    
    public void setIsUpdated(String isUpdated) {
        this.isUpdated = isUpdated;
    }
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }




}


