package hibernate.entity;
// Generated May 14, 2014 9:49:53 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private int semesterId;
     private Curriculum curriculum;
     private String semesterName;
     private Set<Classs> classses = new HashSet<Classs>(0);

    public Semester() {
    }

	
    public Semester(int semesterId, String semesterName) {
        this.semesterId = semesterId;
        this.semesterName = semesterName;
    }
    public Semester(int semesterId, Curriculum curriculum, String semesterName, Set<Classs> classses) {
       this.semesterId = semesterId;
       this.curriculum = curriculum;
       this.semesterName = semesterName;
       this.classses = classses;
    }
   
    public int getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(int semesterId) {
        this.semesterId = semesterId;
    }
    public Curriculum getCurriculum() {
        return this.curriculum;
    }
    
    public void setCurriculum(Curriculum curriculum) {
        this.curriculum = curriculum;
    }
    public String getSemesterName() {
        return this.semesterName;
    }
    
    public void setSemesterName(String semesterName) {
        this.semesterName = semesterName;
    }
    public Set<Classs> getClassses() {
        return this.classses;
    }
    
    public void setClassses(Set<Classs> classses) {
        this.classses = classses;
    }




}


