package hibernate.entity;
// Generated May 15, 2014 10:06:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private Integer semesterId;
     private Curriculum curriculum;
     private String semesterName;
     private Set<Classs> classses = new HashSet<Classs>(0);

    public Semester() {
    }

	
    public Semester(String semesterName) {
        this.semesterName = semesterName;
    }
    public Semester(Curriculum curriculum, String semesterName, Set<Classs> classses) {
       this.curriculum = curriculum;
       this.semesterName = semesterName;
       this.classses = classses;
    }
   
    public Integer getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }
    public Curriculum getCurriculum() {
        return this.curriculum;
    }
    
    public void setCurriculum(Curriculum curriculum) {
        this.curriculum = curriculum;
    }
    public String getSemesterName() {
        return this.semesterName;
    }
    
    public void setSemesterName(String semesterName) {
        this.semesterName = semesterName;
    }
    public Set<Classs> getClassses() {
        return this.classses;
    }
    
    public void setClassses(Set<Classs> classses) {
        this.classses = classses;
    }




}


