package hibernate.entity;
// Generated May 30, 2014 8:57:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SemesterSubject generated by hbm2java
 */
public class SemesterSubject  implements java.io.Serializable {


     private int semSubjId;
     private CurriculumSemester curriculumSemester;
     private Subjects subjects;
     private Set<Marks> markses = new HashSet<Marks>(0);

    public SemesterSubject() {
    }

	
    public SemesterSubject(int semSubjId) {
        this.semSubjId = semSubjId;
    }
    public SemesterSubject(int semSubjId, CurriculumSemester curriculumSemester, Subjects subjects, Set<Marks> markses) {
       this.semSubjId = semSubjId;
       this.curriculumSemester = curriculumSemester;
       this.subjects = subjects;
       this.markses = markses;
    }
   
    public int getSemSubjId() {
        return this.semSubjId;
    }
    
    public void setSemSubjId(int semSubjId) {
        this.semSubjId = semSubjId;
    }
    public CurriculumSemester getCurriculumSemester() {
        return this.curriculumSemester;
    }
    
    public void setCurriculumSemester(CurriculumSemester curriculumSemester) {
        this.curriculumSemester = curriculumSemester;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }




}


