package hibernate.entity;
// Generated May 18, 2014 12:37:30 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Semester generated by hbm2java
 */
public class Semester  implements java.io.Serializable {


     private int semesterId;
     private Curriculum curriculum;
     private String semesterName;
     private String term;
     private Set<Subjects> subjectses = new HashSet<Subjects>(0);

    public Semester() {
    }

	
    public Semester(int semesterId, String semesterName) {
        this.semesterId = semesterId;
        this.semesterName = semesterName;
    }
    public Semester(int semesterId, Curriculum curriculum, String semesterName, String term, Set<Subjects> subjectses) {
       this.semesterId = semesterId;
       this.curriculum = curriculum;
       this.semesterName = semesterName;
       this.term = term;
       this.subjectses = subjectses;
    }
   
    public int getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(int semesterId) {
        this.semesterId = semesterId;
    }
    public Curriculum getCurriculum() {
        return this.curriculum;
    }
    
    public void setCurriculum(Curriculum curriculum) {
        this.curriculum = curriculum;
    }
    public String getSemesterName() {
        return this.semesterName;
    }
    
    public void setSemesterName(String semesterName) {
        this.semesterName = semesterName;
    }
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }
    public Set<Subjects> getSubjectses() {
        return this.subjectses;
    }
    
    public void setSubjectses(Set<Subjects> subjectses) {
        this.subjectses = subjectses;
    }




}


