package hibernate.entity;
// Generated May 15, 2014 10:06:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subjects generated by hbm2java
 */
public class Subjects  implements java.io.Serializable {


     private Integer subjectId;
     private String subjectName;
     private Integer minMark;
     private Integer maxMark;
     private Set<Marks> marks = new HashSet<Marks>(0);

    public Subjects() {
    }

	
    public Subjects(String subjectName) {
        this.subjectName = subjectName;
    }
    public Subjects(String subjectName, Integer minMark, Integer maxMark, Set<Marks> marks) {
       this.subjectName = subjectName;
       this.minMark = minMark;
       this.maxMark = maxMark;
       this.marks = marks;
    }
   
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Integer getMinMark() {
        return this.minMark;
    }
    
    public void setMinMark(Integer minMark) {
        this.minMark = minMark;
    }
    public Integer getMaxMark() {
        return this.maxMark;
    }
    
    public void setMaxMark(Integer maxMark) {
        this.maxMark = maxMark;
    }
    public Set<Marks> getMarks() {
        return this.marks;
    }
    
    public void setMarks(Set<Marks> marks) {
        this.marks = marks;
    }




}


