package hibernate.entity;
// Generated May 14, 2014 9:49:53 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Subjects generated by hbm2java
 */
public class Subjects  implements java.io.Serializable {


     private int subjectId;
     private String subjectName;
     private Integer minMark;
     private Integer maxMark;
     private Set<Mark> marks = new HashSet<Mark>(0);

    public Subjects() {
    }

	
    public Subjects(int subjectId, String subjectName) {
        this.subjectId = subjectId;
        this.subjectName = subjectName;
    }
    public Subjects(int subjectId, String subjectName, Integer minMark, Integer maxMark, Set<Mark> marks) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.minMark = minMark;
       this.maxMark = maxMark;
       this.marks = marks;
    }
   
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Integer getMinMark() {
        return this.minMark;
    }
    
    public void setMinMark(Integer minMark) {
        this.minMark = minMark;
    }
    public Integer getMaxMark() {
        return this.maxMark;
    }
    
    public void setMaxMark(Integer maxMark) {
        this.maxMark = maxMark;
    }
    public Set<Mark> getMarks() {
        return this.marks;
    }
    
    public void setMarks(Set<Mark> marks) {
        this.marks = marks;
    }




}


