package hibernate.entity;
// Generated May 18, 2014 12:37:30 PM by Hibernate Tools 3.6.0


import java.io.Serializable;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private String username;
     private String passwords;
     private String roles;

    public Users() {
    }

	
    public Users(int userId, String username, String passwords) {
        this.userId = userId;
        this.username = username;
        this.passwords = passwords;
    }
    public Users(int userId, String username, String passwords, String roles) {
       this.userId = userId;
       this.username = username;
       this.passwords = passwords;
       this.roles = roles;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }




}


